// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WALServiceClient is the client API for WALService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WALServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type wALServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWALServiceClient(cc grpc.ClientConnInterface) WALServiceClient {
	return &wALServiceClient{cc}
}

func (c *wALServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/proto.WALService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WALServiceServer is the server API for WALService service.
// All implementations must embed UnimplementedWALServiceServer
// for forward compatibility
type WALServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedWALServiceServer()
}

// UnimplementedWALServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWALServiceServer struct {
}

func (UnimplementedWALServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedWALServiceServer) mustEmbedUnimplementedWALServiceServer() {}

// UnsafeWALServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WALServiceServer will
// result in compilation errors.
type UnsafeWALServiceServer interface {
	mustEmbedUnimplementedWALServiceServer()
}

func RegisterWALServiceServer(s grpc.ServiceRegistrar, srv WALServiceServer) {
	s.RegisterService(&WALService_ServiceDesc, srv)
}

func _WALService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WALServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WALService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WALServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WALService_ServiceDesc is the grpc.ServiceDesc for WALService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WALService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WALService",
	HandlerType: (*WALServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _WALService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wal.proto",
}
